<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Comment;
use AppBundle\Entity\Product;
use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    /**
     * @param Product $product
     * @return Comment[]|null
     */
    public function getOrderedProductComments(Product $product)
    {
        $queryBuilder = $this->createQueryBuilder('comments');
        $queryBuilder
            ->where($queryBuilder->expr()->eq('comments.product', ':product'))
            ->orderBy('comments.datetime', 'DESC')
            ->setParameter('product', $product)
        ;

        return $queryBuilder->getQuery()->getResult();
    }
}
