<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Product;
use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    /**
     * @param $searchString
     * @return Product[]|null
     */
    public function search($searchString)
    {
        $queryBuilder = $this->createQueryBuilder('p')
            ->addSelect("MATCH_AGAINST (p.title, p.description, :searchString) as score")
            ->where('MATCH_AGAINST(p.title, p.description, :searchString) > 0')
            ->setParameter('searchString', $searchString)
            ->orderBy('score', 'desc')
        ;
        $draftResult = $queryBuilder->getQuery()->getResult();

        return array_column($draftResult, 0);
    }
}
